### ISSUE TITLE
Create RoadMap for the project (wiki)

### ISSUE THREAD

**Issue by b0noI** [b0noI/XO-hexlet#21]

**Comment by b0noI** [comment]
M1 - working prototype of the XO 
M2 - http://m.habrahabr.ru/post/183764/

**Comment by Rende11** [comment]
Done in https://github.com/Rende11/XO-hexlet/commit/f005201b68088d3c40d9b847f450544db737f93a

**Comment by Rende11** [comment]
Add extension for support markdowns https://github.com/b0noI/XO-hexlet/commit/48bc76b8449dfcf2e89e3b68a9126d636927a572
