### ISSUE TITLE
Изменить способ печти разделителя

### ISSUE THREAD

**Issue by b0noI** [b0noI/XO-hexlet#6]
Метод printSeparator должен быть переименован в generateSeparartor со следующей сигнатурой:

generateSeparartor(n: Int, ch: Charatcer): String

на вход принимается длинна разделителя и символ разделителя а на выходе сам разделитель.

Задача включает написание тестов для данного метода.

**Comment by andrewzhurov** [comment]
Done in https://github.com/b0noI/XO-hexlet/commit/583b4f84f989069c377f7254bbd36f53e868d846
